name        : dstat
version     : 0.7.2
release     : 3
source      :
    - http://dag.wieers.com/home-made/dstat/dstat-0.7.2.tar.bz2 : 34a986d9d7c028bd9dcb6b2ef1c740f7220de5c9cf976870a2b62aca23b33bae
homepage    : http://dag.wieers.com/home-made/dstat
license     :
    - GPLv2
summary     : Replacement for vmstat, iostat, netstat, and ifstat
description : |
    Dstat is inteded to be a versatile replacement for vmstat, iostat, netstat, and ifstat by overcoming their limitations, adding extra features, more counters, and flexibilty.
build      : |
    %make
install    : |
    %make_install
