name       : dstat
version    : 0.7.3
release    : 6
source     :
    - https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz : 46e63821857b69fbc60cb2c7d893ccdd6f31cd9ef24b8bb0b68951e1c7374898
homepage   : http://dag.wieers.com/home-made/dstat
license    : GPL-2.0-or-later
component  : system.utils
summary    : Replacement for vmstat, iostat, netstat, and ifstat
description: |
    Dstat is inteded to be a versatile replacement for vmstat, iostat, netstat, and ifstat by overcoming their limitations, adding extra features, more counters, and flexibilty.
build      : |
    %make
install    : |
    %make_install
