name       : dstat
version    : 0.7.4
release    : 8
source     :
    - https://github.com/dagwieers/dstat/archive/v0.7.4.tar.gz : 4fbd58f3461c86d09a3ab97472aa204de37aa33d31a0493a3e5ed86a2045abea
homepage   : http://dag.wieers.com/home-made/dstat
license    : GPL-2.0-or-later
component  : system.utils
summary    : Replacement for vmstat, iostat, netstat, and ifstat
description: |
    Dstat is inteded to be a versatile replacement for vmstat, iostat, netstat, and ifstat by overcoming their limitations, adding extra features, more counters, and flexibilty.
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    %make_install
